config/routes.rb
Rails.application.routes.draw do
  root to: 'users#tops'

  resources :users, except: %i[index destroy] do
    collection do
      get :tops
    end
  end

  resources :pictures do
    collection do
      post :confirm
      get :favor_pictures
    end
  end

  resources :sessions, only: %i[new create destroy]

  resources :favorites, only: [:create, :destroy]

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  validates :content, presence: true
  validates :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  before_validation { email.downcase! }
  mount_uploader :image, ImageUploader
  validates :name, presence: true, length: { maximum: 40 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :pictures
  has_many :favorites, dependent: :destroy
  has_many :favor_pictures, through: :favorites, source: :picture
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  add_flash_types :success, :info, :warning, :danger
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_url, info: "#{favorite.picture.user.name}さんの投稿をお気に入りに追加しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_url, warning: "#{favorite.picture.user.name}さんのお気に入り投稿を解除しました"
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: %i[show edit update destroy]

  def index
    @pictures = Picture.page(params[:page]).per(5).order(created_at: :desc)
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id
    if params[:back]
      render :new
    else
      if @picture.save
        # ConfirmMailer.confirm_mail(@picture).deliver
        redirect_to root_path, success: '投稿しました！'
      else
        render :new
      end
    end
  end

  def show
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end

  def edit
    if @picture.user.id != current_user.id
      redirect_to root_path
    end
  end

  def update
    if @picture.update(picture_params)
      redirect_to picture_path(@picture.id), info: '更新しました！'
    else
      render :edit
    end
  end

  def destroy
    @picture.destroy
    redirect_to root_path, danger: '投稿を削除しました'
  end

  def confirm
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id
    render :new if @picture.invalid?
  end

  def favor_pictures
    @pictures = current_user.favor_pictures
  end

  private

  def picture_params
    params.require(:picture).permit(:image, :image_cache, :content)
  end

  def set_picture
    @picture = Picture.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to root_path, success: 'ログインしました'
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:danger] = 'ログアウトしました'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update]
  def tops
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, success: 'ユーザ登録完了'
    else
      render :new
    end
  end

  def show
  end

  def edit
    if @user.id != current_user.id
      redirect_to root_path
    end
  end

  def update
    if @user.update(user_params)
      redirect_to root_path, info: 'ユーザ情報を更新しました'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :image_cache)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm' || action_name == 'create'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsKadai3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>
      <div class="page-header">
        <h1><%= link_to 'This is Insta 「もどき」', root_path, class: 'header-title' %></h1>
      </div>
    </header>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <%= value.html_safe %>
      </div>
    <% end %>
    <section class="page-main">
      <div class="container">
        <div class="row">
          <div class="col-sm-8">

            <%= yield %>

          </div>
          <div class="col-sm-offset-2 col-sm-2 side-content">
            <h5>このサイトを作った人</h5>
            <%= image_tag 'profile.jpg', size: '200x200' %>
            <p>ぜひ投稿してください！</p>
          </div>
        </div>
      </div>
    </section>
    <footer>
      <nav class="navbar navbar-default navbar-fixed-bottom">
        <div class="container-fluid">
          <nav class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-menu">
              <span class="sr-only">インスタもどき</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>

            <a class="navbar-brand" href="/"><span class="glyphicon glyphicon-home" aria-hidden="true"></span> Home</a>
          </nav>
          <div id="navbar-menu" class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
              <% if logged_in? %>
                <li><%= link_to '投稿一覧', pictures_path %></li>
                <li><%= link_to '新規投稿', new_picture_path %></li>
                <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">マイページ
                  <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to current_user.name + 'さん', user_path(current_user.id) %></li>
                    <li class="divider"></li>
                    <li><%= link_to 'ログアウト', session_path(current_user.id), method: :delete, data: { confirm: 'ログアウトしますか？'} %></li>
                  </ul>
                </li>
              <% else %>
                <li><%= link_to 'ログイン', new_session_path %></li>
                <li><%= link_to '新規登録', new_user_path %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </footer>

  </body>
</html>

app/views/pictures/_form.html.erb
<% if @picture.errors.any? %>
  <p><%= @picture.errors.count %>件のエラーがあります</p>
  <ul>
  <% @picture.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
<% end %>
<%= form_with(model: @picture, local: true, url: choose_new_or_edit) do |f| %>
  <%= image_tag @picture.image.url if @picture.image && @picture.image.url %>
  <%= f.hidden_field :image_cache %>
  <tr>
    <th><%= f.label :image %></th>
    <td><%= f.file_field :image %></td>
  </tr>
  <tr>
    <th><%= f.label :content %></th>
    <td><%= f.text_field :content %></td>
  </tr>
  <%= f.submit %>
<% end %>

app/views/pictures/confirm.html.erb
<h2>この内容で投稿しますか？</h2>

<%= form_with(model: @picture, local: true, url: pictures_path) do |f| %>
  <%= image_tag @picture.image.url if @picture.image && @picture.image.url %>
  <%= f.hidden_field :image_cache %>

  <%= f.hidden_field :content %>
  <p>内容：<%= @picture.content %></p>

  <%= f.submit %>
  <%= f.submit '戻る', name: 'back' %>
<% end %>

app/views/pictures/edit.html.erb
<h2>画像の編集</h2>

<%= render 'form' %>

<%= link_to '詳細画面に戻る', picture_path(@picture.id), class: 'btn btn-primary' %>

app/views/pictures/favor_pictures.html.erb
<div class="main_contents">
  <% if logged_in? %>
    <ul class="nav nav-tabs nav-justified">
    	<li role="presentation"><%= link_to 'ホーム', root_path %></li>
    	<li role="presentation"><%= link_to '投稿一覧', pictures_path %></li>
    	<li role="presentation" class="active"><%= link_to 'お気に入り一覧', favor_pictures_pictures_path %></li>
    </ul>
    <div class="home-contents">
      <% @pictures.each do |pic| %>
        <div class="contents-pictures">
          <%= image_tag pic.image.url %>
          <p>内容：<%= link_to pic.content, picture_path(pic.id) %></p>
          <p>投稿者：<%= pic.user.name %></p>
        </div>
      <% end %>
    </div>
  <% else %>
    <div class="jumbotron">
      <h2>早速<%= link_to 'ログイン', new_session_path %>しよう！</h2>
      <h2>新規登録がまだの方は<%= link_to 'こちら', new_user_path %></h2>
      <h3>現在<%= @users.count %>人の方にユーザ登録いただいております！</h3>
    </div>
  <% end %>
</div>

app/views/pictures/index.html.erb
<div class="main_contents">
  <% if logged_in? %>
    <ul class="nav nav-tabs nav-justified">
    	<li role="presentation"><%= link_to 'ホーム', root_path %></li>
    	<li role="presentation"  class="active"><%= link_to '投稿一覧', pictures_path %></li>
    	<li role="presentation"><%= link_to 'お気に入り一覧', favor_pictures_pictures_path %></li>
    </ul>
  <% else %>
    <div class="jumbotron">
      <h2>早速<%= link_to 'ログイン', new_session_path %>しよう！</h2>
      <h2>新規登録がまだの方は<%= link_to 'こちら', new_user_path %></h2>
      <h3>現在<%= @users.count %>人の方にユーザ登録いただいております！</h3>
    </div>
  <% end %>

  <div class="home-contents">
    <% @pictures.each do |pic| %>
      <div class="contents_pictures">
        <%= image_tag pic.image.url %>
        <p>内容：<%= link_to pic.content, picture_path(pic.id) %></p>
      </div>
    <% end %>
    <%= paginate @pictures %>
  </div>
</div>

app/views/pictures/new.html.erb
<h2>投稿しよう！</h2>

<%= render 'form' %>

<%= link_to 'ホーム', root_path, class: 'btn btn-success' %>

app/views/pictures/show.html.erb
<h2>この画像の詳細</h2>

<%= image_tag @picture.image.url %>
<p>内容：<%= @picture.content %></p>
<p>投稿者：<%= link_to @picture.user.name, user_path(@picture.user.id) %></p>
<p>投稿日：<%= @picture.created_at.strftime("%Y-%m-%d") %></p>

<% if @picture.user_id != current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りに追加', favorites_path(picture_id: @picture.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% else %>
  <%= link_to '投稿を編集する', edit_picture_path(@picture.id), class: 'btn btn-warning' %>
  <%= link_to '投稿を削除する', picture_path(@picture.id), method: :delete, class: 'btn btn-danger', data: { confirm: '本当に削除しますか？' } %>
<% end %>
<%= link_to '投稿一覧に戻る', pictures_path, class: 'btn btn-info' %>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <p><%= @user.errors.count %> 件のエラーがあります</p>
  <ul>
  <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
  <table>
    <tr>
      <th><%= f.label :name %></th>
      <td><%= f.text_field :name %></td>
    </tr>
    <tr>
      <th><%= f.label :email %></th>
      <td><%= f.email_field :email %></td>
    </tr>
    <tr>
      <%= image_tag @user.image.url if @user.image && @user.image.url %>
      <%= f.hidden_field :image_cache %>
      <th><%= f.label :image %></th>
      <td><%= f.file_field :image %></td>
    </tr>
    <tr>
      <th><%= f.label :password %></th>
      <td><%= f.password_field :password %></td>
    </tr>
    <tr>
      <th><%= f.label :password_confirmation %></th>
      <td><%= f.password_field :password_confirmation %></td>
    </tr>
  </table>
  <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<h2>ユーザ情報編集</h2>

<%= render 'form' %>

<%= link_to 'ホーム', root_path, class: 'btn btn-success' %>

app/views/users/new.html.erb
<h2>新規登録はこちらから！</h2>

<%= render 'form' %>

app/views/users/show.html.erb
<h2>ユーザ詳細</h2>
<h3><%= @user.name %>さんのページ</h3>
<div>
  <%= image_tag @user.image.url %>
</div>

<%= link_to 'ホーム', root_path, class: 'btn btn-success' %>

app/views/users/tops.html.erb
<div class="main_contents">
  <% if logged_in? %>
    <ul class="nav nav-tabs nav-justified">
    	<li role="presentation" class="active"><%= link_to 'ホーム', root_path %></li>
    	<li role="presentation"><%= link_to '投稿一覧', pictures_path %></li>
    	<li role="presentation"><%= link_to 'お気に入り一覧', favor_pictures_pictures_path %></li>
    </ul>
    <div class="home-contents">
      <%= image_tag "welcome.jpg", size: "400x300" %>
      <h2><span class="glyphicon glyphicon-camera" aria-hidden="true"></span>
      お気に入りの画像を投稿しよう！</h2>
      <%= link_to '新規投稿', new_picture_path, class: 'btn btn-primary' %>
      <%= link_to 'プロフィール編集', edit_user_path(current_user.id), class: 'btn btn-warning' %>
      <%= link_to 'ログアウト', session_path(current_user.id), method: :delete, class: 'btn btn-danger', data: { confirm: 'ログアウトしますか？'} %>
    </div>
  <% else %>
    <div class="jumbotron">
      <h2>早速<%= link_to 'ログイン', new_session_path %>しよう！</h2>
      <h2>新規登録がまだの方は<%= link_to 'こちら', new_user_path %></h2>
      <h3>現在<%= @users.count %>人の方にユーザ登録いただいております！</h3>
    </div>
  <% end %>
</div>